- README.md
- configure.ac
- src/dnmtools.cpp
- src/utils/format-reads.cpp
Updating the `format` command so that it can identify whether there is a suffix appended to read names in the two different ends for paired-end data.
> Update format command

- .github/workflows/c-cpp.yml
- Makefile.am
- autogen.sh
- configure.ac
- test/test_abismal.test
- test/test_abismalidx.test
- test/test_bsrate.test
- test/test_format.test
- test/test_simreads.test
Added parentheses around `${PWD}`.
> Including tests

- Makefile.am
- added -Wall to CXXFLAGS in `Makefile.am`
- updated submodules.
> Adding wall

- src/analysis/levels.cpp
To determine whether the input file seems to be an original counts file or one that has been filtered either for only CpGs or for symmetric CpGs. The user has the option to allow a "relaxed" mode that will continue, and possibly output results that are incomplete if the file does not include all cytosines.
> Added a check for input file

- src/analysis/pmd.cpp
This is most helpful in catching situations where the input is a well-formed symmetric CpGs counts file, but seems to have no data.
> Adding check for insufficient data in pmd

- src/analysis/methstates.cpp
If the threads are available, they can be used to accelerate decompressing BAM input, but not likely to give much speedup.
> Adding threads to states command for decompression

- src/analysis/roimethstat.cpp
- src/common/MSite.cpp
- src/common/MSite.hpp
Made a function to check whether a file is a methylation file, and used it in `roi`.
> Roi verify input

- .github/workflows/build-docker-image.yml
- Dockerfile
Added Dockerfile and workflow file to build the image. Currently it is only a manual trigger, and the built image is not published. 
We can turn on the publish option once we do testing.
> Deploy container

- .github/workflows/docker-build.yml
- updated the the workflow to apply only to master branch.
- Added an option that, if there is no Dockerfile, it will try to use Dockerfile of the latest commit
> Temp docker

- src/analysis/bsrate.cpp
Adding feature to produce a histogram of per-read conversion rates to the terminal. Internally the summary stats are tabulated in a 2D array to allow for extension later.
> Bsrate per read

- src/analysis/methcounts.cpp
Ensuring that all chromosomes are reported even if some have no reads mapping to them. Ensuring the order of chromosomes is the same as in the header of the SAM file. Adding option to report progress but verbose default does not report for every chromosome. Verifying that chromosome names and sizes are identical in the reference genome and the SAM file header.
> counts: reporting chromosomes without mapped reads

- src/analysis/hmr-rep.cpp
- src/analysis/hmr.cpp
- src/analysis/hypermr.cpp
- src/analysis/levels.cpp
- src/analysis/pmd.cpp
- src/analysis/roimethstat.cpp
- src/common/MSite.cpp
Checking the format of input files that in theory are generated by `dnmtools counts`.
> Msite input validation

- src/utils/symmetric-cpgs.cpp
If input is not sorted, ensuring output file is deleted and reporting the error.
> sym: checking that the input is sorted

- data/md5sum.txt
- src/analysis/metagene.cpp
- src/analysis/roimethstat.cpp
- src/common/LevelsCounter.cpp
- src/common/LevelsCounter.hpp
- src/common/MSite.cpp
- src/common/MSite.hpp
This branch involves changes to some internal behavior that also changes the output of `levels` and `roi` although the initial intent was to improve stability of `roi`.
> Roi improvements

- docs/README.md
- docs/content/hmr.md
- docs/content/pmd.md
- docs/content/uniq.md
- src/analysis/hmr.cpp
- src/analysis/pmd.cpp
- src/utils/uniq.cpp
Created summary functions for `pmd`, `hmr`, and `uniq`.
> Pmd summary

- src/amrfinder/amrfinder.cpp
- src/analysis/methstates.cpp
- src/common/Epiread.cpp
- src/common/Epiread.hpp
- src/common/MSite.cpp
- src/utils/symmetric-cpgs.cpp
Adding gzip output option for sym and fixing the gzip option for states which did not work when output to standard output.
> sym and states: gzip option

- src/utils/guessprotocol.cpp
- Added a probabilistic model for the read to be T-rich or A-rich
- Updated the criteria for guessing the protocol
- Documented the summary data
> Guessprotocol updates

- src/amrfinder/amrfinder.cpp
- src/amrfinder/amrtester.cpp
- src/common/EpireadStats.cpp
- src/common/EpireadStats.hpp
- src/utils/guessprotocol.cpp
- Code optimizations
- Refactoring to allow for multiple threads
> amrfinder optimization

- src/analysis/hmr-rep.cpp
- src/analysis/hmr.cpp
- src/analysis/levels.cpp
- src/analysis/metagene.cpp
- src/analysis/methcounts.cpp
- src/common/EpireadStats.cpp
- src/common/TwoStateHMM.cpp
- src/common/TwoStateHMM_PMD.cpp
- src/common/bam_record_utils.cpp
More warnings when using clang from conda on osx.
> Silencing warnings (round two)

- Makefile.am
- src/amrfinder/amrfinder.cpp
- src/common/dnmtools_utils.cpp
- src/common/dnmtools_utils.hpp
- Adding dnmtools_utils source files which might be temporary. They are used right now only to do things related to summary stats output from the commands
- Adding dnmtools_utils.chpp files to Makefile.am
- Formatting some code
- amrfinder: Adding the uniform summary output options and format
> uniform summary arguments

- src/analysis/pmd.cpp
Ensuring that summary info, if requested, is written even if there is insufficient data.
> PMD write summary on error

- src/analysis/hmr.cpp
hmr: ensuring that summary data is written even when data is insufficient to identify HMRs
> HMRs summary on insufficient data

- src/utils/covered.cpp
- updating submodule bamxx
- covered: using input file compression mode to determine output file compression mode
- covered.cpp: formatting
> covered compression mode

- src/amrfinder/amrfinder.cpp
Accounted for the case with few cpgs compared to window size.
> Debug amrfinder

- data/md5sum.txt
- docs/content/environment.yaml
- docs/requirements.txt
- src/abismal: updating submodule
- Updating the requirements.txt file for readthedocs because of github complaints about jinja version
- md5sum.txt: updating hashes for new version of abismal
- Again: Updating the requirements.txt file for jinja version which was included twice
- docs/content/environment.yaml: Updating for jinja version
> abismal submodule update

- src/dnmtools.cpp
- src/utils/merge-methcounts.cpp
- merge: fixing some cli descriptions
- src/dnmtools.cpp: fixing a cli description
> fixing malformed usage messages

- src/analysis/roimethstat.cpp
- src/smithlab_cpp: updating submodule for raw about messages in option parser
- src/analysis/roimethstat.cpp: using the raw mode for help messages to display more information about the output
> More help info printed for roi command

- Makefile.am
- src/analysis/cpgbins.cpp
- src/dnmtools.cpp
Adding the cpgbins command to generate the same format as the roi command but with the input being xcounts format and assuming CpG sites. This should be faster than using roi on an input file of bins
> Adding cpgbins command

- src/utils/clean-hairpins.cpp
Major updates to the code for clean hairpins for organization, efficiency and total inforamtion provided
> Clean hairpins update

- src/common/bam_record_utils.cpp
Adding some const, removing unused variables and throwing a previously unthrown exception
> Linting source dealing with BAM files

- README.md
- configure.ac
- data/md5sum.txt
- docs/content/quickstart.md
Changes in this PR involve versions, submodules and test output hashes
> Updates ahead of release v1.4.4

- src/analysis/methentropy.cpp
Previously multiple fasta files, one per chrom, were assumed. Now it takes one reference genome fasta file
> Updating the input format for the entropy command

- Makefile.am
- src/analysis/autocorr.cpp
- src/dnmtools.cpp
This command generates information about autocorrelation of methylation
> Adding autocorr command
