smithlabcode/dnmtools

Makefile.am, src/analysis/methcounts.cpp, src/common/dnmt_error.hpp, src/dnmtools.cpp
Modifying code for the `counts` command to use bgzf output format and directly read HTSlib format BAM/SAM files so both kinds of IO can use threads. Additional optimizations for speed.
=> Counts bgzf

src/analysis/levels.cpp
In `levels.cpp`: The function that validates content of input file assumes the file is not zipped, but the input allows for gz compressed counts file.
=> Bug in levels testing file format

Makefile.am, src/radmeth/methdiff.cpp, src/radmeth/radmeth.cpp, src/radmeth/radmeth_model.hpp, src/radmeth/radmeth_optimize.cpp, src/radmeth/radmeth_optimize.hpp
Moved the GSL code for regression, which uses general miltidimensional minization, into separate source files. The purpose of this is to eventually eliminate the use of GSL. Also, the `gsl_sflnchoose` in `methdiff.cpp` was replaced with a fully written function that uses the standard lgamma.
=> Radmeth gsl isolation

src/amrfinder/allelicmeth.cpp, src/amrfinder/amrfinder.cpp, src/amrfinder/amrtester.cpp, src/analysis/methstates.cpp, src/common/Epiread.cpp, src/common/Epiread.hpp
Updates to the following commands: `states`, `amrfinder` and `amrtester`. Most of these have to do with input format verification, but also some minor efficiency improvements and cleaning up code.
=> Amrfinder: several udpates

src/utils/uniq.cpp
This functionality is not expected to be the typical use of the `uniq` command, but it is helpful in some situations. The modifications are minimal, and only involve accepting user input and adding an aux field to the BAM record before it is written to output.
=> uniq: functionality to tag each read with its duplicate count

src/analysis/bsrate.cpp, src/common/bam_record_utils.cpp, src/utils/format-reads.cpp
Updated code that works in the `format` command to catch more possible errors in the data while trying to standardize the format of mapped reads from bsmap.
=> Format bsmap

src/analysis/methcounts.cpp, src/analysis/methstates.cpp, src/analysis/roimethstat.cpp, src/common/MSite.cpp, src/utils/format-reads.cpp
Added my name to the files I contributed to.
=> Added my credits

src/utils/selectsites.cpp
Ensuring that selectsites will not attempt to do binary search on disk within the counts file if it's in compressed format.
=> Selectsites input file type

src/common/bam_record_utils.cpp
Leak was in to_string for bamxx::bam_rec using bamxx::bam_header. Memory to pull the string kstring_t was not released.
=> Fixing memory leak

docs/content/diff.md, src/radmeth/methdiff.cpp
Updating the `diff` command. The sites must be sorted, and this is checked in both files, but their chromosome order need only be consistent with each other. Sites will now be synchronized so that sites differing between the two inputs are ignored, but as long as sites are sorted in a consistent way between the two inputs, the sites in common will be processed.
=> diff comand: sites sorted and syncd

src/common/LevelsCounter.hpp
Adding comments to `LevelsCounter.hpp` so that the values output for levels are properly defined
=> Comments to define values output for variables

docs/content/roi.md
Closes #147. Adding some updates to the docs to ensure users know that the numbers of sites in the output are determined by the content of the counts input file, and not be the reference genome.
=> roi: update to docs

src/utils/selectsites.cpp
Adding a summary output file and making output code more uniform using bgzf output format even when not compressed.
=> selectsites: zipped output and summary

src/analysis/bsrate.cpp, src/analysis/hmr.cpp, src/analysis/pmd.cpp, src/common/LevelsCounter.cpp, src/common/LevelsCounter.hpp
Fixing problem with macOS not allowing comparison between unsigned long and uint64_t by static casting ul to uint64_t.
=> Fixing problem because of macOS

src/analysis/pmd.cpp
Moving exit statement on insufficient data out of the check for verbose mode.
=> Fixes 156: pmd bug

data/md5sum.txt
Updating submodules abismal and smithlab_cpp. The update for abismal should allow CXXFLAGS to be specified on the command line without interfering with the required AM_CXXFLAGS, which will give us the flexibility to build on conda's systems by spexifying the additional define to compensate for the lacking c++17 support in macos compilers.
=> Updating submodules

src/amrfinder/amrfinder.cpp, src/analysis/bsrate.cpp, src/analysis/hmr-rep.cpp, src/analysis/hmr.cpp, src/analysis/hypermr.cpp, src/analysis/multimethstat.cpp, src/analysis/pmd.cpp, src/common/EpireadStats.cpp, src/common/MSite.cpp, src/common/ThreeStateHMM.cpp, src/common/TwoStateHMM.cpp, src/common/TwoStateHMM_PMD.cpp, src/common/TwoStateHMM_PMD.hpp, src/utils/format-reads.cpp, src/utils/uniq.cpp
- EpireadStats: removing constexpr as it's not always supported yet for the way it was used
- bsrate: adding to_string around an integer that was concatenated to a string
- MSite.cpp: putting a guard around use of from_chars because on osx it is not yet available from c++17
- amrfinder.cpp: ensuring move is std::move because it must be explicit fir some compilers. Also casting properly for size_t seeming to be unsigned long long on apple
- Removing unused variables to silence warnings. In some cases these seem to have been important
- amrfinder: Fixing a warning issues by using decltype in a static cast
- ThreeStateHMM: putting guards around backward score as it's only used to compare with forward score in debug situation within assert
- Fixes #169.
- pmd: many places the vector …
=> silencing compiler warnings

data/md5sum.txt, src/amrfinder/amrfinder.cpp, src/amrfinder/amrtester.cpp, src/common/EpireadStats.cpp, src/common/EpireadStats.hpp
- smithlab_cpp: updating submodule
- amrfinder: added an option to turn off the correction to likelihood for the number of reads which is applied to the likelihood for the two alleles model
- EpireadStats.hpp: changing the EpireadStats class to struct and allowing default values for default constructor. Also adding an instance variable to indicate whether log likelihood for allel pair model should correct for number of reads
- EpireadStats.cpp: adding a variable to control the use of correction to the allele pair model log likelihood based on number of reads
- amrfinder.cpp: Using the default constructor for EpireadStats
- amrtester: using an approach more similar to amrfinder which uses the EpireadStats class instance and allows a correction for read count for the allel pair model log …
=> amrfinder correct for read counts

Makefile.am, src/analysis/methcounts.cpp, src/common/MSite.cpp, src/common/MSite.hpp, src/common/bam_record_utils.hpp, src/dnmtools.cpp, src/utils/covered.cpp, src/utils/recovered.cpp, src/utils/symmetric-cpgs.cpp, src/utils/unxcounts.cpp, src/utils/xcounts.cpp
- methcounts.cpp: adding option to include a header in the counts output
- covered.cpp: minor fix in output when no args given
- symmetric-cpgs.cpp: added a function to print any header if it exists, which involves just printing leading lines that begin with # symbol
- bam_record_utils.hpp: added a function to get the target length from the header without specifying the internal header inside the bam_header object
- MSite.hpp and MSite.cpp: added a constructor from a char array with length. Also moved the logic of parsing strings to construct MSite into an initialize function which allows the same thing to be done without constructing a new object
- xcounts.cpp: adding this file to compress the counts files as small as possible
- dnmtools.cpp: adding the xcounts command
- Makefile.am: …
=> compress counts

src/analysis/pmd.cpp, src/common/counts_header.cpp, src/common/counts_header.hpp, src/utils/xcounts.cpp
- xcounts.cpp and counts_header.hpp and cpp: fixing a typo in a function name
- pmd.cpp: if the fraction of bins passing after finding a bin size by the dynamic method is still not high enough, the bin size is set to numeric limits max
=> pmd guarantee coverage

src/common/counts_header.cpp, src/common/counts_header.hpp, src/utils/xcounts.cpp
- added option to specify header file for xcounts
- xcounts: ensuring a header is found either by the user providing a reference genome, the user directly providing a header, or the header already existing in the counts file
=> xcounts header prepend

src/analysis/pmd.cpp, src/common/TwoStateHMM_PMD.cpp
- src/common/TwoStatHMM_PMD.cpp: Formatting code
- src/analysis/pmd.cpp: adding an additional check for sufficient data after filtering bins based on deserts
- src/analysis/pmd.cpp: changing the min required bins for inference to be 100. It's not clear if this is important because the bins after filtering will be sufficient if the data is good, and if this is a problem, the number of bins will be extremely small
=> pmd fix insufficient data after filter

src/common/MSite.hpp, src/utils/unxcounts.cpp
- src/common/MSite.hpp: reorganizing the class definition and constructor that takes all instance vars in order
- src/utils/unxcounts.cpp: adding functionality for counts files that only include symmetric cpgs sites
=> unxcounts for sym

src/utils/unxcounts.cpp
Bug: When the input is symmetric CpG sites and the user requests non-covered sites to be in the output file, all cytosines were being reported. This was not the desired behavior. It also made no sense, because even if all those sites were desired, the guanine next to the C in CpG would be present, but its data would also be present on the site beside it
=> Bugfix for unxcount

src/analysis/cpgbins.cpp, src/common/counts_header.cpp, src/utils/covered.cpp, src/utils/unxcounts.cpp, src/utils/xcounts.cpp
This submodule update consolidates code that reads lines from bgzf files and removes and updates functions in several source files of the current repo
=> Updating bamxx submodule

Makefile.am, src/analysis/cpgbins.cpp, src/common/xcounts_utils.cpp, src/common/xcounts_utils.hpp
Adding the xcounts_utils.cpp source file with functionality that will be used by both cpgbins and roi when the input is in xcounts format
=> Adding xcounts_utils.cpp source file

src/analysis/roimethstat.cpp
Adding the code for the roi command to accept xsym format input. This requires sequentially loading all the sites, and a completely separate branch from the other input format options. It also requires testing the input formt to determine if it is xsym, and the branch for xsym takes priority. This behavior should be updated so that the user specifies to prevent any unexpected behavior
=> roi accepts xsym input

src/analysis/roimethstat.cpp
Ensuring that if a name on an input region already exists it will be retained in the output
=> roi default region name

src/utils/kmersites.cpp
Since kmersites is intended to create tracks for the ucsc genome browser, the offset argument should default to 1 since we usually want to change the 0-based chromosomal positions to 1-based for the standard in wigToBigWig.
=> One-based variable-step bigWig in kmersites

src/utils/merge-methcounts.cpp
This bug checked that the read count for a site was greater than instead of greater than or equal to the min reads specified by the user for allowing integer counts to converted to a fractional value between 0 and 1
=> Bugfix in min reads for fraction in merge command

src/common/counts_header.cpp, src/common/counts_header.hpp, src/utils/xcounts.cpp
Ensuring that chrom order within reference/header and counts file are the same when running xcounts
=> Chrom order checks in xcounts

src/analysis/bsrate.cpp, src/analysis/methcounts.cpp, src/utils/format-reads.cpp, src/utils/uniq.cpp
This is done by simply skipping the reads for which tid is -1 and completely ignoring them
=> Allowing unmapped reads in counts, bsrate, format and uniq

Makefile.am, data/md5sum.txt, src/analysis/nanopore.cpp, src/common/MSite.cpp, src/common/MSite.hpp, src/common/bam_record_utils.cpp, src/dnmtools.cpp, src/utils/symmetric-cpgs.cpp
Added the counts-nano command to process BAM files from nanopore with a default check on the base caller and updated the sym command to work with methylation levels that don't correspond to integers relative to the total number of reads
=> Counts for nanopore reads with both 5mC and 5hmC

configure.ac
Needs to be able to link with static libs including htslib which needs pthreads and libz; also updated similarly in submodule for abismal
=> Updating build config for making binaries

Makefile.am, configure.ac, data/md5sum.txt, src/common/bam_record_utils.cpp, src/common/bam_record_utils.hpp, src/common/dnmtools_utils.cpp, src/common/dnmtools_utils.hpp, src/utils/format-reads.cpp
SAM orientation reverse complements reads that map to the negative strand. Abismal can now output in strict SAM format if a flag is given. This PR adds the functionality in the format command to accept the strict SAM format.
=> Adding flag to format command for reads in SAM orientation

src/radmeth/radmeth.cpp, src/radmeth/radmeth_model.cpp, src/radmeth/radmeth_model.hpp, src/radmeth/radmeth_optimize.cpp
Implemented a novel algorithm for computing the likelihood and for computing the likelihood's gradient for the beta binomial with general design
=> Radmeth performance improvements

src/amrfinder/amrfinder.cpp
The bug manifested when there were more threads used than chromosomes, and threads were assigned to chromosomes, with some receiving undefined ranges of data
=> Amrfinder threads bugfix

src/radmeth/radmeth.cpp, src/radmeth/radmeth_model.cpp, src/radmeth/radmeth_model.hpp
This will help allow radmeth to run even if the order of sample names differs between the design matrix and the data matrix, and even if the design matrix has extra samples
=> radmeth sample consistency between design and data matrix
